ptut_platform_homepage:
    path:     /home
    defaults: { _controller: PTUTPlatformBundle:Platform:index }
    
ptut_redirect:
    path: /
    defaults: { _controller: PTUTPlatformBundle:Platform:redirect} 
    
ptut_platform_view:
    path:     /page/{id}
    defaults: { _controller: PTUTPlatformBundle:Platform:view }
    
ptut_platform_view_id:
    path:     /actualites/{id}
    defaults: { _controller: PTUTPlatformBundle:Platform:viewid }

ptut_platform_article:
    path:     /article/{id}
    defaults: { _controller: PTUTPlatformBundle:Platform:view_article }

ptut_platform_article_creator:
    path: /admin/creer
    defaults: { _controller: PTUTPlatformBundle:Platform:article_creator }