Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        presentation:
            type: string
            nullable: false
            length: 3000
            options:
                fixed: false
        date:
            type: date
            nullable: false
        auteur:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        commentaires:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
